### PR TITLE
Feature- Migrate to lerna yarn workspaces

### PR DESCRIPTION
**Pull request by aptcore**
**Description**
In this PR I have transformed the project into a combination of lerna + yarn workspaces, allowing lerna to manage the low level details of the yarn workspaces (they talk the same language).

I have achieved:
- Creation of 3 packages: regen-app/web, regen-app/web-components, regen-app/web-storybook.
- TS linting is done by eslint.
- TS is now blazing fast when developing the react app and also the storybook.
- The amount of config has been reduced drastically
- Packages are now separated properly
- Libraries have been updated
- I have successfully connected the web-component's Table in a storybook story inside web
- The storybook works fine!  

**Note for developers**
Interesting blog posts:
-  https://yarnpkg.com/blog/2018/02/15/nohoist/
-  https://doppelmutzi.github.io/monorepo-lerna-yarn-workspaces/

### CODE REVIEW

**Comment by aaronc** [comment]
@aptcore is this ready to merge yet or still a draft?

**Comment by aaronc** [comment]
@aptcore I think I mostly fixed CI. Now the app deploy works. The storybook build looks like it has a legitimate error.

**Comment by aaronc** [comment]
@aptcore I think I mostly fixed CI. Now the app deploy works. The storybook build looks like it has a legitimate error:

```
1:32:58 PM: web-storybook: ERR! Module not found: Error: Can't resolve 'web-components/lib/components/table' in '/opt/build/repo/web/src'
1:32:58 PM: web-storybook: (node:1304) UnhandledPromiseRejectionWarning: ModuleNotFoundError: Module not found: Error: Can't resolve 'web-components/lib/components/table' in '/opt/build/repo/web/src'
1:32:58 PM: web-storybook:     at factory.create (/opt/build/repo/node_modules/webpack/lib/Compilation.js:823:10)
1:32:58 PM: web-storybook:     at factory (/opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
1:32:58 PM: web-storybook:     at resolver (/opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
1:32:58 PM: web-storybook:     at asyncLib.parallel (/opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
1:32:58 PM: web-storybook:     at /opt/build/repo/node_modules/neo-async/async.js:2830:7
1:32:58 PM: web-storybook:     at /opt/build/repo/node_modules/neo-async/async.js:6877:13
1:32:58 PM: web-storybook:     at normalResolver.resolve (/opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
1:32:58 PM: web-storybook:     at doResolve (/opt/build/repo/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
1:32:58 PM: web-storybook:     at hook.callAsync (/opt/build/repo/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
1:32:58 PM: web-storybook:     at _fn0 (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
1:32:58 PM: web-storybook:     at resolver.doResolve (/opt/build/repo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
1:32:58 PM: web-storybook:     at hook.callAsync (/opt/build/repo/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
1:32:58 PM: web-storybook:     at _fn0 (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
1:32:58 PM: web-storybook:     at hook.callAsync (/opt/build/repo/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
1:32:58 PM: web-storybook:     at _fn0 (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
1:32:58 PM: web-storybook:     at resolver.doResolve (/opt/build/repo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
1:32:58 PM: web-storybook: (node:1304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
1:32:58 PM: web-storybook: (node:1304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aptcore** [comment]
Sorry @aaronc I missed your message. This error is odd to me I have just run:
`git clean -xdf && yarn install && yarn build && yarn storybook` in the project's root folder and worked fine.

Based on the error description I guess you have not run `yarn build` before. Am I right?

**Comment by aaronc** [comment]
> Sorry @aaronc I missed your message. This error is odd to me I have just run:
> `git clean -xdf && yarn install && yarn build && yarn storybook` in the project's root folder and worked fine.
> 
> Based on the error description I guess you have not run `yarn build` before. Am I right?

This is for running `yarn build-storybook`

**Pull request merged**
